import { constants, privateDecrypt } from 'crypto';

export interface DecryptedDiscoursePayload {
  key?: string;
  nonce?: string;
  push?: boolean;
  api?: number | string;
  expires_at?: string;
}

function normalizeEncryptedPayload(value: string): string {
  let payload = value.trim();
  try {
    if (/^https?:\/\//i.test(payload)) payload = new URL(payload).searchParams.get('payload') || payload;
    else if (/^payload=/i.test(payload)) payload = new URLSearchParams(payload).get('payload') || payload;
    payload = decodeURIComponent(payload);
  } catch {
    // The raw base64 payload needs no URL decoding.
  }
  return payload.replace(/ /g, '+').replace(/[\r\n\t]/g, '');
}

export function decryptDiscoursePayload(
  encryptedPayload: string,
  privateKeyPem: string,
): DecryptedDiscoursePayload {
  const encrypted = Buffer.from(normalizeEncryptedPayload(encryptedPayload), 'base64');
  const errors: string[] = [];

  for (const padding of [constants.RSA_PKCS1_OAEP_PADDING, constants.RSA_PKCS1_PADDING]) {
    try {
      const decrypted = privateDecrypt({ key: privateKeyPem, padding }, encrypted);
      return JSON.parse(decrypted.toString('utf8')) as DecryptedDiscoursePayload;
    } catch (err) {
      errors.push(err instanceof Error ? err.message : String(err));
    }
  }

  throw new Error(`Authorization code could not be decrypted. Make sure you paste the code generated by the most recent authorization attempt. ${errors[0] || ''}`.trim());
}
