import '../server/load-env';

import express from 'express';
import cors from 'cors';
import topicsRouter from '../server/routes/topics';
import previewRouter from '../server/routes/preview';
import publishRouter from '../server/routes/publish';
import configRouter from '../server/routes/config';
import historyRouter from '../server/routes/history';
import commsRouter from '../server/routes/comms';
import composerRouter from '../server/routes/composer';
import webinarsRouter from '../server/routes/webinars';
import syncRouter from '../server/routes/sync';
import communityAgentRouter from '../server/routes/community-agent';
import dmReviewRouter from '../server/routes/dm-review';
import cronRouter from '../server/routes/cron';
import operationsRouter from '../server/routes/operations';
import automationRouter from '../server/routes/automation';
import dailySummaryRouter from '../server/routes/daily-summary';
import reviewQueueRouter from '../server/routes/review-queue';
import sandboxRouter from '../server/routes/sandbox';
import memoryRouter from '../server/routes/memory';
import usageRouter from '../server/routes/usage';
import qualityRouter from '../server/routes/quality';
import pushRouter from '../server/routes/push';
import platformRouter from '../server/routes/platform';
import discourseAuthRouter from '../server/routes/discourse-auth';
import { attachProjectContext } from '../server/auth';
import { apiRateLimit, protectWorkspaceApi, securityHeaders } from '../server/security';

const app = express();
app.use(securityHeaders);
app.use(cors());
app.use(express.json({ limit: '18mb' }));
app.use('/api', apiRateLimit);
app.use(attachProjectContext);
app.use('/api', protectWorkspaceApi);

app.use('/api/platform', platformRouter);
app.use('/api/discourse-auth', discourseAuthRouter);
app.use('/api/topics', topicsRouter);
app.use('/api/preview', previewRouter);
app.use('/api/publish', publishRouter);
app.use('/api/config', configRouter);
app.use('/api/history', historyRouter);
app.use('/api/comms', commsRouter);
app.use('/api/composer', composerRouter);
app.use('/api/webinars', webinarsRouter);
app.use('/api/sync', syncRouter);
app.use('/api/community-agent', communityAgentRouter);
app.use('/api/dm-review', dmReviewRouter);
app.use('/api/cron', cronRouter);
app.use('/api/operations', operationsRouter);
app.use('/api/automation', automationRouter);
app.use('/api/daily-summary', dailySummaryRouter);
app.use('/api/review-queue', reviewQueueRouter);
app.use('/api/sandbox', sandboxRouter);
app.use('/api/memory', memoryRouter);
app.use('/api/usage', usageRouter);
app.use('/api/quality', qualityRouter);
app.use('/api/push', pushRouter);

export default app;
